version: "3"
services:
  backend:
    container_name: "backend"
    build: 
      context: ../
      dockerfile: Dockerfile
    env_file: ../.env
    ports:
      - "3001:3001"
    depends_on:
      - postgres

  postgres:
    container_name: "database"
    image: "postgres:12"
    env_file: ../.env

