# Stage 1: Build the app
FROM node:16-alpine as builder
WORKDIR /app
COPY package*.json ./
RUN npm i --omit=dev
COPY . .
RUN ls -la

RUN npm run build

# Stage 2: Create the production image
FROM node:16-alpine as production
WORKDIR /app
COPY --from=builder /app/package*.json ./
RUN npm i --omit=dev
COPY --from=builder /app/dist/ .

# Remove dev dependencies
RUN npm prune --production

CMD ["node", "/dist/main.js"]
